# Prometheus main configuration
# This configuration is adapted for Docker Compose environment

global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
    metrics_path: /metrics

  # Scrape cAdvisor
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Scrape Node Exporter
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:9090"]
