name: Build and Push Grafana Observability

on:
  push:
    tags:
      - "grafana-v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-push:
    uses: ./.github/workflows/action-build-and-push.yaml
    permissions:
      contents: read
      packages: write
    with:
      image_name: observability/grafana
      build_context: ./observability/grafana
      file_path: ./observability/grafana/Dockerfile
