name: Build and Push Loki Database

on:
  push:
    tags:
      - "loki-v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-push:
    uses: ./.github/workflows/action-build-and-push.yaml
    permissions:
      contents: read
      packages: write
    with:
      image_name: observability/loki
      build_context: ./observability/loki
      file_path: ./observability/loki/Dockerfile
